### PR TITLE
Update for oid_path_length function + docs + spec

### PR DESCRIPTION
**Pull request by axrayn**
@colinsurprenant 

Another quick one - adding oid_path_length config option and related functionality and the associated docs and specs to cover it.

### CODE REVIEW

**Comment by colinsurprenant** [comment]
Great! thanks @axrayn 
👀

**Comment by colinsurprenant** [comment]
LGTM

**Comment by axrayn** [comment]
@colinsurprenant Do we need anything else on this one before merge+publish?

**Comment by colinsurprenant** [comment]
@axrayn no - all good - lets move forward.

**Comment by colinsurprenant** [comment]
v1.2.0 published - thanks for you work on this @axrayn !!

**Pull request merged**
