### PR TITLE
SNMP Table support addition

### PR DESCRIPTION
**Pull request by axrayn**
@colinsurprenant Here's the PR for table support and bumps the version to 1.0.2.

This doesn't include the support for a config option to split table results rather than users relying on the split filter.

### CODE REVIEW

**Comment by colinsurprenant** [comment]
thanks a lot @axrayn - looking at this!

**Comment by colinsurprenant** [comment]
Overall looks great! only thing missing are some specs :P 
I agree this plugin has a quite low coverage to start with, we should nonetheless at least add specs for the option parsing similar to what we have in the `snmp_spec.rb` file. 
Otherwise, tests around the `getTable` operation can wait until we introduce a mock snmp server for these. 
@axrayn let me know if you can/want to look into this or you'd like me to help with that.

**Comment by axrayn** [comment]
Oops, my bad! I'll go through and see if I can add some specs and shout out if I get stuck.

**Comment by axrayn** [comment]
@colinsurprenant Added specs for both the walk and tables functions (and then proceeded to git push before I'd commited the changes :man_facepalming:  )

**Comment by colinsurprenant** [comment]
@axrayn perfect! all code change LGTM! 🎉 
A few more minor changes I'd like you to do:
- I suggest we bump to 1.1.0 instead of 1.0.2, this is more than a bugfix! 
- Please add yourself in the `CONTRIBUTORS` file

Also, could you squash all code commits into one and the "version" related changes (`logstash-input-snmp.gemspec`, `CHANGELOG`, `CONTRIBUTORS`) into another commit with description "bump to version 1.1.0" ? 

Let me know if you need help with git-fu for squashing etc. 

Once the above is in I will merge and publish this!

**Comment by colinsurprenant** [comment]
LGTM. Let's merge & publish! :shipit: 
Great work @axrayn  - thanks a lot for your contribution!

**Comment by colinsurprenant** [comment]
v1.1.0 published and available for install. 
I just realized we forgot to update `docs/` will open a followup issue /cc @karenzone

**Comment by piellick** [comment]
> @colinsurprenant Here's the PR for table support and bumps the version to 1.0.2.
> 
> This doesn't include the support for a config option to split table results rather than users relying on the split filter.

Hi Everyone , great jobs table support work great !

Some one could provide a kv filter or split filter exemple to extract values of each SNMP index inside a document ?

exemple of table input : 
`{
  "1": 1,
  "2": "1.3.6.1.4.1.8708.2.30.2.3.1.1.2.1.76",
  "3": "1.3.6.1.4.1.8708.2.30.2.3.1.1.2.1.76",
  "4": "FDXXXXXXXXXXXXX",
  "5": 0,
  "6": 0,
  "7": 0,
  "8": 0,
  "9": "L2 service operation status is down",
  "10": 5,
  "11": "FDXXXXXXXXXXXXX",
  "12": "FDXXXXXXXXXXXXX",
  "13": 1,
  "14": "FDXXXXXXXXXXXXX",
  "15": "0.0.0.0",
  "index": "1"
},
{
  "1": 2,
  "2": "1.3.6.1.4.1.8708.2.5.2.5.1.0",
  "3": "1.3.6.1.4.1.8708.2.5.2.5.7.0",
  "4": "upload",
  "5": 0,
  "6": 0,
  "7": 1,
  "8": 4,
  "9": "Upload failed",
  "10": 4,
  "11": "FDXXXXXXXXXXXXX",
  "12": "0FDXXXXXXXXXXXXX",
  "13": 2,
  "14": "FDXXXXXXXXXXXXX",
  "15": "FDXXXXXXXXXXXXX",
  "index": "2"
}`


i will propose a PR to update document just after. 👍

**Comment by karenzone** [comment]
Thanks for advocating for quality docs, @colinsurprenant. 
@piellick, thanks for opening the docs PR.  When it's ready, please include me as a reviewer, too.

**Pull request merged**
