### PR TITLE
Docs: example on setting IPv6 hosts 

### PR DESCRIPTION
**Pull request by kares**
including specs that verify IPv6 hosts are parsed fine by snmp4j

### CODE REVIEW

**Comment by kares** [comment]
seems to me like we do not need anything special to handle IPv6 hosts (https://github.com/logstash-plugins/logstash-input-snmp/pull/88) ... but maybe I've missed something.

**Comment by colinsurprenant** [comment]
Great! We should manually test it to make sure nothing is missing.

**Comment by colinsurprenant** [comment]
(until we have an integration tests setup in place - see #87).

**Comment by kares** [comment]
this is tested and confirmed to be working (the `udp6:` used by snmpd is not a valid syntax for snmp4j).
happy to merge as is for docs to be picked up in the next release or do we want bump+changelog due the docs change?

**Comment by colinsurprenant** [comment]
➕1️⃣   bump+changelog!

**Pull request merged**
