### PR TITLE
separate general input option vs SNMPv3 specific options

### PR DESCRIPTION
**Pull request by colinsurprenant**
followup on #36

### CODE REVIEW

**Comment by colinsurprenant** [comment]
LMKWYT @karenzone!

**Comment by axrayn** [comment]
Should there be a reference to setting 'aes' being equivalent to setting 'aes128' just so there's no doubt/confusion?

**Comment by colinsurprenant** [comment]
@axrayn good point. will do. thanks!

**Comment by karenzone** [comment]
@colinsurprenant   I still need to make changes to support no_codec conditional, so I can bump versions at that time if that works for you.

**Pull request merged**
